version: '3.8'
services:
  backend:
    image: "ashrafulsohag/provisioning:latest"
    deploy:
      replicas: 3
      placement:
        constraints:
        - node.role == worker
    environment:
      VM_NAME: "{{.Node.Hostname}}"
    ports:
    - target: 8085
      published: 8085
      mode: host # Ensures request goes directly to the node
    networks:
    - swarm-network

  visualizer:
    image: dockersamples/visualizer:latest
    deploy:
      placement:
        constraints:
        - node.role == manager
    ports:
    - "9000:8080"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
    - swarm-network

networks:
  swarm-network:
    driver: overlay
