version: '3.8'
services:
  springboot-app:
    image: "ashrafulsohag/provisioning:latest"
    deploy:
      replicas: 3
      placement:
        constraints:
        - node.role == worker
    environment:
      VM_NAME: "{{.Node.Hostname}}"
    ports:
    - target: 8085
      published: 8085
      mode: host # Ensures request goes directly to the node
    networks:
    - swarm-network

networks:
  swarm-network:
    driver: overlay
