version: '3.8'
services:
  springboot-app:
    image: "ashrafulsohag/provisioning:latest"
    deploy:
      endpoint_mode: dnsrr
      replicas: 3
      placement:
        constraints:
          - node.role == worker
    environment:
      VM_NAME: "{{.Node.Hostname}}"
    ports:
      - "8085:8085"
    networks:
      - swarm-network

networks:
  swarm-network:
    driver: overlay
