global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - 'node-exporter:9100'

  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - 'cadvisor:8080'

  - job_name: 'backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - '192.168.123.11:8085'
          - '192.168.123.12:8085'
          - '192.168.123.13:8085'