global:
  scrape_interval: 10s

scrape_configs:
- job_name: 'node-exporter'
  static_configs:
  - targets:
    - '192.168.123.11:9100'
    - '192.168.123.12:9100'
    - '192.168.123.13:9100'
    - '192.168.123.14:9100'
  relabel_configs:
  - source_labels: [ __address__ ]
    target_label: __param_target
  - source_labels: [ __param_target ]
    target_label: instance
  - target_label: node # Adds a 'node' label
    replacement: "node-$1" # Custom naming pattern
    action: replace
    source_labels: [ __meta_docker_container_name ]
  - target_label: hostname
    replacement: "${1}"
    action: replace
    source_labels: [ __address__ ]
    regex: '([^:]+)(:\d+)?'

- job_name: 'cadvisor'
  static_configs:
  - targets:
    - '192.168.123.11:8080'
    - '192.168.123.12:8080'
    - '192.168.123.13:8080'
    - '192.168.123.14:8080'

- job_name: 'backend'
  metrics_path: '/actuator/prometheus'
  static_configs:
  - targets:
    - '192.168.123.11:8085'
    - '192.168.123.12:8085'
    - '192.168.123.13:8085'
