global:
  scrape_interval: 10s

scrape_configs:
- job_name: 'node-exporter-vm1'
  static_configs:
  - targets:
    - '192.168.123.11:9100'

- job_name: 'node-exporter-vm2'
  static_configs:
  - targets:
    - '192.168.123.12:9100'

- job_name: 'node-exporter-vm3'
  static_configs:
  - targets:
    - '192.168.123.13:9100'

- job_name: 'node-exporter-vm4'
  static_configs:
  - targets:
    - '192.168.123.14:9100'

- job_name: 'cadvisor'
  static_configs:
  - targets:
    - '192.168.123.11:8080'
    - '192.168.123.12:8080'
    - '192.168.123.13:8080'
    - '192.168.123.14:8080'

- job_name: 'backend-vm1'
  metrics_path: '/actuator/prometheus'
  static_configs:
  - targets:
    - '192.168.123.11:8085'

- job_name: 'backend-vm2'
  metrics_path: '/actuator/prometheus'
  static_configs:
  - targets:
    - '192.168.123.12:8085'

- job_name: 'backend-vm3'
  metrics_path: '/actuator/prometheus'
  static_configs:
  - targets:
    - '192.168.123.13:8085'
