---
- name: Deploy Spring Boot Stack
  hosts: vm4

  vars:
    git_commit_hash: "{{ git_commit_hash }}"

  tasks:
  - name: Display latest commit hash
    ansible.builtin.debug:
      msg: "Deploying by commit: {{ git_commit_hash }}"

  - name: Ensure backend app directory exists
    ansible.builtin.file:
      path: /home/manager/backend
      state: directory
      mode: '0755'

  - name: Ensure observability directory exists
    ansible.builtin.file:
      path: /home/manager/observability
      state: directory
      mode: '0755'

  - name: Copy static stack file
    ansible.builtin.copy:
      src: ../docker-stack.yml
      dest: /home/manager/backend/docker-stack.yml

  - name: Copy observability folder with all its content
    ansible.builtin.copy:
      src: ../observability/
      dest: /home/manager/observability/
      mode: '0644'
      directory_mode: '0755'
      recurse: true

  #    - name: Install jsondiff for Docker Stack module
  #      become: true
  #      ansible.builtin.pip:
  #        name: jsondiff
  #        state: present

  - name: Replace placeholder with commit hash
    ansible.builtin.replace:
      path: /home/manager/springboot-app/docker-stack.yml
      regexp: 'COMMIT_HASH_PLACEHOLDER'
      replace: "{{ git_commit_hash }}"

  - name: Deploy stack
    community.docker.docker_stack:
      name: provision-service
      state: present
      compose:
      - /home/manager/springboot-app/docker-stack.yml
