---
- name: Deploy Spring Boot Stack
  hosts: vm4
  tasks:
    - name: Ensure deployment directory exists
      ansible.builtin.file:
        path: /home/manager/springboot-app
        state: directory
        mode: '0755'

    - name: Copy static stack file
      ansible.builtin.copy:
        src: ../docker-stack.yml
        dest: /home/manager/springboot-app/docker-stack.yml

    - name: Install required system packages for docker_stack
      apt:
        name:
          - python3-jsondiff
          - python3-docker
        state: present
        update_cache: yes

    - name: Deploy stack
      community.docker.docker_stack:
        name: provision-service
        state: present
        compose:
          - /home/manager/springboot-app/docker-stack.yml